PolyDAQ: task_sd_card Class Reference
task_sd_card Class Reference
Task which saves data to an SD card.
#include <task_sd_card.h>
Public Member Functions
task_sd_card (const char *p_name, unsigned portBASE_TYPE prio, size_t stacked, emstream *serpt)
Creates a SD card interface task object.
void run (void)
The run method that saves data to an SD card.
void write_header (emstream *p_ser_dev)
Write a header showing data items to be logged to a serial device.
Detailed Description
Task which saves data to an SD card.
This task saves data to an SD card. The data is transferred to this task as a stream of bytes in a queue.
Definition at line 86 of file task_sd_card.h.
Constructor & Destructor Documentation
task_sd_card::task_sd_card (const char * p_name, unsigned portBASE_TYPE prio, size_t stacked, emstream * serpt)
Creates a SD card interface task object.
This constructor calls its parent class's constructor to actually do the work of creating a task object.
Parameters
p_name A name for this task
prio The priority at which this task will run (should be low)
stacked The stack space to be used by the task (not much)
serpt A pointer to a serial device on which debugging messages are shown
Definition at line 45 of file task_sd_card.cpp.
Member Function Documentation
void task_sd_card::run (void)
The run method that saves data to an SD card.
This run method waits for an SD card to be inserted in the socket. When a card is found in the socket, it opens a data file using an automatically generated, sequenced name. Then data which arrives in the data queue is saved to the card as soon as the data arrives.
Definition at line 82 of file task_sd_card.cpp.
References DATA_F_EXT, DATA_F_NAME, logger_config::get_ticks_per_sample(), logger_config::is_valid(), p_led_command_queue, p_logger_config, p_sd_card_text_queue, p_ticks_per_sd_data, logger_config::read(), sd_card_LED, SD_TSK_DBG, and write_header().
void task_sd_card::write_header (emstream * p_ser_dev)
Write a header showing data items to be logged to a serial device.
This method writes a header line which shows the name of each of the items to be logged. Usually the logging is done to an SD card, and this line is a header for the logged data. The logger configuration object, which is pointed to by the shared variable p_logger_config, is used to get the data headers.
Parameters
p_ser_dev A pointer to the serial device to which to write the header
Definition at line 283 of file task_sd_card.cpp.
References logger_config::get_first_channel(), logger_config::get_next_channel(), logger_col_cfg::p_label, and p_logger_config.
Referenced by run().
The documentation for this class was generated from the following files:
task_sd_card.h
task_sd_card.cpp