PolyDAQ: task_sd_daq Class Reference
task_sd_daq Class Reference
Task which acquires PolyDAQ data for the SD card.
#include <task_sd_daq.h>
Public Member Functions
task_sd_daq (const char *name, unsigned portBASE_TYPE prio, size_t stacked, emstream *serpt, polydaq2 *p_polydaq2)
This constructor creates a SD card data acquisition task.
Protected Member Functions
void acquire_sd_data (logger_config *p_log_config)
Take one row of data for the SD card.
void run (void)
The run method that runs the data acquisition task code.
Protected Attributes
portTickType ticks_per_sample
The number of milliseconds per sample taken by this task.
polydaq2 * my_poly
Pointer to a PolyDAQ driver used by this task.
Detailed Description
Task which acquires PolyDAQ data for the SD card.
This task acquires data. It is run at a high priority so that data can be taken at precise time intervals. The data is then put into a queue so that it can be written to an SD card at a rate at which the card can accept it.
Definition at line 59 of file task_sd_daq.h.
Constructor & Destructor Documentation
task_sd_daq::task_sd_daq (const char * p_name, unsigned portBASE_TYPE prio, size_t stacked, emstream * serpt, polydaq2 * p_polydaq2)
This constructor creates a SD card data acquisition task.
This constructor calls its parent class's constructor to actually do the work of creating a data acquisition task.
Parameters
p_name A name for this task
prio The priority at which this task will run (should be low)
stacked The stack space to be used by the task (not much)
serpt A pointer to a serial device on which debugging messages are shown
p_polydaq2 A pointer to the PolyDAQ 2 driver used to interface with the data acquisition board
Definition at line 44 of file task_sd_daq.cpp.
References my_poly, and ticks_per_sample.
Member Function Documentation
void task_sd_daq::acquire_sd_data (logger_config * p_log_config) protected
Take one row of data for the SD card.
This method acquires one row of data for the SD card and places the text representing the data into the SD card's text queue. The SD card task will write the data to the card when it can.
Parameters
p_log_config Pointer to the data logger configuration object to be used
Definition at line 64 of file task_sd_daq.cpp.
References logger_col_cfg::command, DAQ_EOL, polydaq2::get_data(), logger_config::get_first_channel(), logger_config::get_next_channel(), my_poly, logger_col_cfg::offset, p_led_command_queue, p_sd_card_text_queue, and logger_col_cfg::slope.
Referenced by run().
void task_sd_daq::run (void) protected
The run method that runs the data acquisition task code.
This method sets up the A/D converter, then waits for a signal to take data. Then it takes data and fills up a buffer with that data.
Definition at line 98 of file task_sd_daq.cpp.
References acquire_sd_data(), logger_config::get_ticks_per_sample(), polydaq2::initialize(), my_poly, and p_logger_config.
The documentation for this class was generated from the following files:
task_sd_daq.h
task_sd_daq.cpp