PolyDAQ: polydaq2 Class Reference
polydaq2 Class Reference
Class which interacts with PolyDAQ 2 hardware.
#include <polydaq2.h>
Public Member Functions
polydaq2 (emstream *serpt)
Create a PolyDAQ 2 interface object.
void initialize (void)
Initialize components which need to be set up after the RTOS is started.
int16_t get_data (char command)
Get and return raw data from one data channel.
int16_t get_data_oversampled (char command, uint8_t samples)
Get and return oversampled raw data from one data channel.
int16_t strain_raw (uint8_t channel)
Get a raw A/D reading from a strain gauge amplifier.
int16_t strain_raw_oversampled (uint8_t channel, uint8_t samples)
Get an oversampled raw A/D reading from a strain gauge amplifier.
int16_t strain_auto_balance (uint8_t channel, uint16_t desired_set=(ADC_MAX_OUTPUT/2))
Automatically zero a strain gauge bridge using the D/A converter.
void strain_balancer_off (void)
Turn the D/A's which are used to balance the strain gauge bridges off.
void strain_balancer_on (void)
Turn the D/A's which are used to balance the strain gauge bridges on.
int16_t voltage_raw (uint8_t channel)
Get a raw voltage reading from the voltage amplifier.
int16_t temperature_raw (uint8_t channel)
Get a raw temperature reading from a thermocouple amplifier.
int16_t read_ADC (uint8_t channel)
Read the given channel from the A/D converter.
void set_DAC (uint8_t channel, uint16_t value)
Set the output of the given D/A channel to the given value.
uint16_t get_prev_DAC_output (uint8_t channel)
Get the value most recently sent to the given D/A channel.
void init_SD_card_LED (void)
Initialize the SD card's LED to be used with PWM for fancy effects.
void set_SD_card_LED_brightness (uint16_t brightness)
Set the brightness of the SD card indicator LED.
int16_t get_accel (uint8_t axis)
Read one channel of the PolyDAQ's accelerometer.
int16_t get_ext_accel (uint8_t channel)
Read one channel of an externally attached MMA8452Q accelerometer.
void set_accel_range (mma8452q_range_t range)
Set the accelerometer's range to +/-2, +/-4, or +/-8 g's.
uint16_t get_IR_temperature (void)
Query the MLX90614 infrared thermometer for a temperature reading.
void scan_I2C_bus (emstream *p_ser_pt)
Check all possible addresses on the I2C bus for sensors.
Protected Attributes
simple_DAC * p_dac
adc_driver * p_adc
emstream * p_serial
uint16_t previous_DAC_output [2]
The value most recently sent to each digital to analog channel.
i2c_master * p_i2c
A pointer to the I2C bus on the PolyDAQ board.
mma8452q * p_accel
A pointer to the MMA8452Q accelerometer on the board, if there is one.
mma8452q * p_ext_accel
A pointer to the extra external MMA8452Q accelerometer, if present.
Detailed Description
Class which interacts with PolyDAQ 2 hardware.
This class contains a set of utility functions which interact with the hardware on a PolyDAQ 2 board. This includes taking readings of voltage, temperature and strain; balancing the strain gauge bridges using the D/A converters; saving data on a MicroSD card; and other things which haven't been written yet.
Definition at line 145 of file polydaq2.h.
Constructor & Destructor Documentation
polydaq2::polydaq2 (emstream * serpt = NULL)
Create a PolyDAQ 2 interface object.
This constructor creates a new PolyDAQ 2 driver object. It saves pointers and creates new analog to digital and digital to analog converter driver objects.
Parameters
serpt A pointer to a serial port that can be used for debugging (default: NULL, meaning no debugging messages will be sent).
Definition at line 38 of file polydaq2.cpp.
References p_accel, p_adc, p_dac, p_ext_accel, p_i2c, p_serial, PDQ_EXT_MMA8452Q_ADDR, PDQ_MMA8452Q_ADDR, and set_DAC().
Member Function Documentation
int16_t polydaq2::get_accel (uint8_t channel)
Read one channel of the PolyDAQ's accelerometer.
This function reads one channel of the accelerometer, if one is present. If the PolyDAQ is configured not to use an accelerometer, this method returns zero.
Parameters
channel The accelerometer channel to read: X = 0, Y = 1, and Z = 2
Returns
The accelerometer reading from the given channel or 0 if there's no accelerometer
Definition at line 504 of file polydaq2.cpp.
References p_accel.
Referenced by get_data(), and task_data_acq::run_daq_command().
int16_t polydaq2::get_data (char command)
Get and return raw data from one data channel.
This method acquires data from one of the available data channels and returns it. Channels may include an A/D converter, an accelerometer axis, or whatever other data source may be configured here.
Parameters
command A one-character command such as '6' to get A/D channel 6 data
Returns
The raw data read from the given channel
Definition at line 105 of file polydaq2.cpp.
References get_accel(), get_ext_accel(), and read_ADC().
Referenced by task_sd_daq::acquire_sd_data(), get_data_oversampled(), task_user::run(), and task_data_acq::run_daq_command().
int16_t polydaq2::get_data_oversampled (char command, uint8_t samples)
Get and return oversampled raw data from one data channel.
Get and return raw data from one data channel.
This method acquires data from one of the available data channels and returns it. Channels may include an A/D converter, an accelerometer axis, or whatever other data source may be configured here.
Parameters
command A one-character command such as '6' to get A/D channel 6 data
samples The number of readings to average in the oversampling process
Returns
The raw data read from the given channel
Definition at line 147 of file polydaq2.cpp.
References get_data().
Referenced by task_user::run().
int16_t polydaq2::get_ext_accel (uint8_t channel)
Read one channel of an externally attached MMA8452Q accelerometer.
This function reads one channel of the external accelerometer, if one is present. If the PolyDAQ is configured not to use an accelerometer or there is no external accelerometer connected, this method returns zero.
Parameters
channel The accelerometer channel to read: x = 0, y = 1, and z = 2
Returns
The accelerometer reading from the given channel or 0 if there's no accelerometer there
Definition at line 524 of file polydaq2.cpp.
References p_accel, and p_ext_accel.
Referenced by get_data().
uint16_t polydaq2::get_IR_temperature (void)
Query the MLX90614 infrared thermometer for a temperature reading.
If a Melexis MLX90614 infrared thermometer is present, this method will ask the sensor for a reading.
Returns
The temperature measured by the IR sensor in the MLX90614.
Definition at line 541 of file polydaq2.cpp.
References p_i2c, and PDQ_MLX90614_ADDR.
Referenced by task_user::run().
uint16_t polydaq2::get_prev_DAC_output (uint8_t channel) inline
Get the value most recently sent to the given D/A channel.
Parameters
channel The channel, 1 or 2, whose output is to be returned
Definition at line 238 of file polydaq2.h.
References previous_DAC_output.
void polydaq2::init_SD_card_LED (void)
Initialize the SD card's LED to be used with PWM for fancy effects.
This method initializes the LED which is used to indicate SD card status (or to indicate something else if desired). The LED is connected to a timer and GPIO pin specified in constants that are given in polydaq2.h.
Definition at line 423 of file polydaq2.cpp.
References SD_CARD_LED_MAX_PWM, SD_LED_CLOCK, SD_LED_OC_INIT_FN, SD_LED_OC_PRNF, SD_LED_PIN, SD_LED_PORT, SD_LED_SET_DUTY, SD_LED_SOURCE, SD_LED_TIMER, and SD_LED_TIMER_CLOCK.
Referenced by task_leds::run().
void polydaq2::initialize (void)
Initialize components which need to be set up after the RTOS is started.
This method sets up PolyDAQ 2 components which cannot be set up until the RTOS has been started. For example, and A/D converter and anything on the I2C bus can only be accessed with the RTOS running because a mutex is used to protect each such component and RTOS delays may be used in some code.
Definition at line 78 of file polydaq2.cpp.
References p_accel, p_ext_accel, p_i2c, and p_serial.
Referenced by task_sd_daq::run().
int16_t polydaq2::read_ADC (uint8_t channel) inline
Read the given channel from the A/D converter.
This method performs an A/D conversion on the given channel of the A/D converter, returning the raw binary number given by the A/D.
Parameters
channel The A/D channel to be read, from 0 to 15 (internal STM32 voltage and temperature channels are not supported)
Returns
The raw binary number returned by the A/D when it read the voltage on the given channel
Definition at line 218 of file polydaq2.h.
References p_adc.
Referenced by get_data().
void polydaq2::scan_I2C_bus (emstream * p_ser_pt) inline
Check all possible addresses on the I2C bus for sensors.
This method calls the I2C's scan method, which prints a table of I2C bus addresses and whether a sensor has been found at each one.
Definition at line 269 of file polydaq2.h.
References p_i2c.
Referenced by task_user::run().
void polydaq2::set_DAC (uint8_t channel, uint16_t value) inline
Set the output of the given D/A channel to the given value.
This method calls the PolyDAQ 2's D/A converter driver, telling it to set the output of one of its channels to the requested value.
Parameters
channel The D/A channel whose output is to be set, 1 or 2
value The value to be put in the D/A's output buffer
Definition at line 229 of file polydaq2.h.
References p_dac, and previous_DAC_output.
Referenced by polydaq2(), task_user::run(), and strain_auto_balance().
void polydaq2::set_SD_card_LED_brightness (uint16_t brightness)
Set the brightness of the SD card indicator LED.
This method sets the brightness of the LED which is used as an indicator of SD card activity. This LED may be used as a general purpose indicator if the SD card is not used.
Parameters
brightness The brightness at which the LED will shine, from 0 to SD_CARD_LED_MAX_PWM (which is usually 1000)
Definition at line 482 of file polydaq2.cpp.
References SD_CARD_LED_MAX_PWM, and SD_LED_SET_DUTY.
Referenced by task_leds::off(), task_leds::on(), and task_leds::run().
int16_t polydaq2::strain_auto_balance (uint8_t channel, uint16_t desired_set = (ADC_MAX_OUTPUT / 2))
Automatically zero a strain gauge bridge using the D/A converter.
This method uses the D/A converter in the STM32 to balance ("zero") a strain gauge bridge. Each strain gauge bridge has a D/A converter output connected to one side through a large (20K nominal) resistor; the voltage from the D/A is used to tweak the bridge output so that the zero-strain reading is as specified in desired_set. A typical value for desired_set is 2047, which is half the full scale for a 12-bit A/D converter; such a zero setting allows positive and negative strains to be measured. It is assumed that strain is zero when this method is called.
Parameters
channel The strain bridge channel to balance ("zero"), either 1 or 2
desired_set The A/D reading which is desired from the bridge amplifier when strain is zero (default value: ADC_MAX_OUTPUT / 2)
Returns
The zero-strain reading which was actually achieved; this may be slightly off the desired value if the system is noisy. If it isn't possible to balance the bridge, (-1) is returned
Definition at line 288 of file polydaq2.cpp.
References p_serial, set_DAC(), strain_balance_retries, strain_balance_tolerance, and strain_raw_oversampled().
Referenced by task_user::run(), and task_data_acq::run_daq_command().
void polydaq2::strain_balancer_off (void)
Turn the D/A's which are used to balance the strain gauge bridges off.
This method deactivates the D/A converters attached to the strain gauge bridge and leaves the D/A pins set as analog inputs. This means that the pins float; they will not affect the voltage on the corners of the bridge. This setting saves a little bit of power.
Definition at line 231 of file polydaq2.cpp.
References p_dac.
void polydaq2::strain_balancer_on (void)
Turn the D/A's which are used to balance the strain gauge bridges on.
This method reactivates the D/A;s attached to a strain gauge bridge after the D/A's were deactivated by a call to strain_balancer_off().
Definition at line 243 of file polydaq2.cpp.
References p_dac.
int16_t polydaq2::strain_raw (uint8_t channel)
Get a raw A/D reading from a strain gauge amplifier.
This method gets an A/D reading from a channel connected to a strain gauge bridge amplifier on a PolyDAQ 2. The channels are connected as follows:
Strain gauge bridge 1 - A/D channel 14, pin PC4
Strain gauge bridge 2 - A/D channel 15, pin PC5
Parameters
channel The strain bridge channel to read, either 1 or 2
Returns
The unscaled, uncalibrated A/D converter output for the given reading, or (-1) if the channel requested was invalid
Definition at line 171 of file polydaq2.cpp.
References p_adc, and p_serial.
int16_t polydaq2::strain_raw_oversampled (uint8_t channel, uint8_t samples)
Get an oversampled raw A/D reading from a strain gauge amplifier.
This method takes a bunch of A/D readings from a channel connected to a strain gauge bridge amplifier on a PolyDAQ 2, then computes the average reading and returns it. The channels are connected as follows:
Strain gauge bridge 1 - A/D channel 14, pin PC4
Strain gauge bridge 2 - A/D channel 15, pin PC5 Oversampling is a conceptually simple way to provide low-pass filtering, usually used to reduce noise in measurements.
Parameters
channel The strain bridge channel to read, either 1 or 2
samples The number of samples to take before computing the average. A maximum of
Returns
The unscaled, uncalibrated A/D converter output for the given reading, or (-1) if the channel requested was invalid
Definition at line 202 of file polydaq2.cpp.
References p_adc, and p_serial.
Referenced by strain_auto_balance().
int16_t polydaq2::temperature_raw (uint8_t channel)
Get a raw temperature reading from a thermocouple amplifier.
This method returns the A/D output when the given thermocouple amplifier channel is read.
Parameters
channel The thermocouple channel to be read, 1 or 2
Returns
The unscaled, uncalibrated A/D converter output for the given reading
Definition at line 402 of file polydaq2.cpp.
References p_adc, and p_serial.
int16_t polydaq2::voltage_raw (uint8_t channel)
Get a raw voltage reading from the voltage amplifier.
This method returns the output of the A/D converter when it reads the given voltage channel on the PolyDAQ 2. Voltage channels 1, 2, 3, and 4 on the circuit board are connected to A/D channels 10, 11, 12, and 13 on the microcontroller.
Parameters
channel The channel whose voltage is to be measured
Returns
The unscaled, uncalibrated A/D converter output for the given channel or (-1) if something went terribly wrong
Definition at line 380 of file polydaq2.cpp.
References p_adc, and p_serial.
Member Data Documentation
adc_driver* polydaq2::p_adc protected
This pointer points to an A/D converter driver which is created by the PolyDAQ driver.
Definition at line 156 of file polydaq2.h.
Referenced by polydaq2(), read_ADC(), strain_raw(), strain_raw_oversampled(), temperature_raw(), and voltage_raw().
simple_DAC* polydaq2::p_dac protected
This pointer allows access to a D/A converter driver created by the PolyDAQ driver.
Definition at line 151 of file polydaq2.h.
Referenced by polydaq2(), set_DAC(), strain_balancer_off(), and strain_balancer_on().
emstream* polydaq2::p_serial protected
This pointer points to a serial port which can be used for debugging. If left at NULL, debugging printouts won't take place.
Definition at line 161 of file polydaq2.h.
Referenced by initialize(), polydaq2(), strain_auto_balance(), strain_raw(), strain_raw_oversampled(), temperature_raw(), and voltage_raw().
The documentation for this class was generated from the following files:
polydaq2.h
polydaq2.cpp