PolyDAQ: task_user Class Reference
task_user Class Reference
Task for communication with the user or a PC based user interface.
#include <task_user.h>
Public Member Functions
task_user (const char *name, unsigned portBASE_TYPE prio, size_t stacked, emstream *serpt, polydaq2 *p_poly_driver)
Creates a user interface task object.
void run (void)
The run method that runs the user interface thread.
void show_help (void)
Show a help menu for the user interface.
Protected Attributes
polydaq2 * p_poly
Pointer to the PolyDAQ 2 board driver from which to get data.
Detailed Description
Task for communication with the user or a PC based user interface.
This task interacts with the user. User input, which may be input from another computer, such as a PC running interface software written in Python, Matlab(tm) or LabView(tm), is usually given as single character commands. The user interface responds with whatever the designer wishes to send to the user or other computer. The use of states is optional, unless this task implements the "vi" editor, in which case it's pretty much mandatory.
Definition at line 45 of file task_user.h.
Constructor & Destructor Documentation
task_user::task_user (const char * p_name, unsigned portBASE_TYPE prio, size_t stacked, emstream * serpt, polydaq2 * p_poly_driver)
Creates a user interface task object.
This constructor calls its parent class's constructor to actually do the work of creating a user interface task object.
Parameters
p_name A name for this task
prio The priority at which this task will run (should be low)
stacked The stack space to be used by the task (quite a bit, actually)
serpt A pointer to a serial device on which debugging messages are shown
p_poly_driver Pointer to a PolyDAQ 2 driver which runs the PolyDAQ board
Definition at line 43 of file task_user.cpp.
References p_poly.
Member Function Documentation
void task_user::run (void)
The run method that runs the user interface thread.
This method checks for characters typed by the user and responds to any typed characters.
Returns
This method should never return; if it hypothetically did, it would return an OS message of zero.
Definition at line 88 of file task_user.cpp.
References polydaq2::get_data(), polydaq2::get_data_oversampled(), polydaq2::get_IR_temperature(), p_daq_UI_command_queue, p_main_text_queue, p_poly, polydaq2::scan_I2C_bus(), polydaq2::set_DAC(), show_help(), polydaq2::strain_auto_balance(), and VERSION_STRING.
void task_user::show_help (void)
Show a help menu for the user interface.
This method writes a list of commands and their functions so that a user can see how to make the program do whatever it can do.
Definition at line 57 of file task_user.cpp.
Referenced by run().
The documentation for this class was generated from the following files:
task_user.h
task_user.cpp