PolyDAQ: task_data_acq Class Reference
task_data_acq Class Reference
Task which acquires PolyDAQ data at precise time intervals.
#include <task_data_acq.h>
Public Member Functions
task_data_acq (const char *name, unsigned portBASE_TYPE prio, size_t stacked, emstream *serpt, polydaq2 *p_polydaq2)
This constructor creates a data acquisition task.
Protected Member Functions
void run_daq_command (char ch_in)
Run a command from the DAQ command queue.
void run (void)
The run method that runs the data acquisition task code.
Protected Attributes
portTickType ms_per_sample
The number of milliseconds per sample taken by this task.
polydaq2 * my_poly
Pointer to a PolyDAQ driver used by this task.
char last_data_channel
Data channel which was most recently read, or (-1) for none.
Detailed Description
Task which acquires PolyDAQ data at precise time intervals.
This task acquires data. It is run at a high priority so that data can be taken at precise time intervals. The data is then put into queues so that other tasks can print the data through a serial port, store the data onto an SD card, or do whatever else is needed.
Definition at line 59 of file task_data_acq.h.
Constructor & Destructor Documentation
task_data_acq::task_data_acq (const char * p_name, unsigned portBASE_TYPE prio, size_t stacked, emstream * serpt, polydaq2 * p_polydaq2)
This constructor creates a data acquisition task.
This constructor calls its parent class's constructor to actually do the work of creating a data acquisition task.
Parameters
p_name A name for this task
prio The priority at which this task will run (should be low)
stacked The stack space to be used by the task (not much)
serpt A pointer to a serial device on which debugging messages are shown
p_polydaq2 A pointer to the PolyDAQ 2 driver used to interface with the data acquisition board
Definition at line 50 of file task_data_acq.cpp.
References last_data_channel, ms_per_sample, and my_poly.
Member Function Documentation
void task_data_acq::run (void) protected
The run method that runs the data acquisition task code.
This method sets up the A/D converter, then waits for a signal to take data. Then it takes data and fills up a buffer with that data.
Definition at line 118 of file task_data_acq.cpp.
References p_daq_UI_command_queue, and run_daq_command().
void task_data_acq::run_daq_command (char ch_in) protected
Run a command from the DAQ command queue.
This method runs a command which has been found in the DAQ command queue. The command will have been sent from the UI task, task_user.
Parameters
ch_in A character containing the command to be run
Definition at line 72 of file task_data_acq.cpp.
References polydaq2::get_accel(), polydaq2::get_data(), last_data_channel, my_poly, and polydaq2::strain_auto_balance().
Referenced by run().
The documentation for this class was generated from the following files:
task_data_acq.h
task_data_acq.cpp