FurutaPendulum: main.c File Reference
main.c File Reference
: Main program body
#include "main.h"
#include "stm32f1xx_hal.h"
#include "cmsis_os.h"
#include "trig.h"
#include "math.h"
Macros
#define EWA 0x02
2 bytes Extended Write Address
#define EWD 0x04
4 bytes Extended Write Data
#define EWCS 0x08
2 bytes Extended Write Control and Status
#define ERA 0x0A
2 bytes Extended Read Address
#define ERCS 0x0C
2 bytes Extended Read Control and Status
#define ERD 0x0E
4 bytes Extended Read Data
#define CTRL 0x1E
Address of the control register.
#define ANG 0x20
address of the Angle register
#define STA 0x22
address of the status register
#define FIELD 0x2A
address of the field strength register
#define CDS_KEYCODE 0x46
key needed to start running spi encoder
Functions
void SystemClock_Config (void)
System Clock Configuration.
void StartDefaultTask (void const *argument)
Task that sets up the pins, timers, etc. and run basic constant torque example.
void HAL_TIM_MspPostInit (TIM_HandleTypeDef *htim)
int main (void)
The application entry point.
void pwmOut (uint16_t a, uint16_t b, uint16_t c)
Set PWM duty cycle for a, b, and c outputs (12 bit inputs)
void setMotorTorque (int16_t torque)
When called, update the PWM output to keep specified torque (12 bit)
uint16_t spiWrite (uint8_t addr, uint8_t val)
Writes val to the addr via SPI.
uint16_t spiRead (uint8_t addr)
Reads the value at the given address.
int16_t getNewTorque (int16_t setpoint)
Calculate the torque to return motor to setpoint (using simple P controller)
void HAL_TIM_PeriodElapsedCallback (TIM_HandleTypeDef *htim)
Period elapsed callback in non blocking mode.
void _Error_Handler (char *file, int line)
This function is executed in case of error occurrence.
Variables
SPI_HandleTypeDef hspi1
TIM_HandleTypeDef htim2
TIM_HandleTypeDef htim3
UART_HandleTypeDef huart1
osThreadId defaultTaskHandle
char * debug
Detailed Description
: Main program body
This notice applies to any and all portions of this file that are not between comment pairs USER CODE BEGIN and USER CODE END. Other portions of this file, whether inserted by the user or by software development tools are owned by their respective copyright owners.
Copyright (c) 2018 STMicroelectronics International N.V. All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted, provided that the following conditions are met:
Redistribution of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of STMicroelectronics nor the names of other contributors to this software may be used to endorse or promote products derived from this software without specific written permission.
This software, including modifications and/or derivative works of this software, must execute solely and exclusively on microcontroller or microprocessor devices manufactured by or for STMicroelectronics.
Redistribution and use of this software other than as permitted under this license is void and will automatically terminate your rights under this license.
THIS SOFTWARE IS PROVIDED BY STMICROELECTRONICS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS, IMPLIED OR STATUTORY WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT OF THIRD PARTY INTELLECTUAL PROPERTY RIGHTS ARE DISCLAIMED TO THE FULLEST EXTENT PERMITTED BY LAW. IN NO EVENT SHALL STMICROELECTRONICS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file main.c.
Function Documentation
_Error_Handler()
void _Error_Handler (char * file, int line)
This function is executed in case of error occurrence.
Parameters
file The file name as string.
line The line in file as a number.
Return values
None
Definition at line 679 of file main.c.
Referenced by SystemClock_Config().
getNewTorque()
int16_t getNewTorque (int16_t setpoint)
Calculate the torque to return motor to setpoint (using simple P controller)
This functions returns the torque calculated by a simple P controller that attempts to keep a constant setpoint. The output is not linear with positon, but instead has an adjustment to increase low end values to make sure the motor has enough torque at the low end to reach the target.
Parameters
setpoint The position that the motor tries to maintain (16 bit number)
Returns
The new torque value that should be sent to the motor from -1000 to 1000
Definition at line 547 of file main.c.
HAL_TIM_MspPostInit()
void HAL_TIM_MspPostInit (TIM_HandleTypeDef * htim)
TIM2 GPIO Configuration
PA0-WKUP ---—> TIM2_CH1 PA1 ---—> TIM2_CH2 PA2 ---—> TIM2_CH3
Definition at line 199 of file stm32f1xx_hal_msp.c.
HAL_TIM_PeriodElapsedCallback()
void HAL_TIM_PeriodElapsedCallback (TIM_HandleTypeDef * htim)
Period elapsed callback in non blocking mode.
Note
This function is called when TIM4 interrupt took place, inside HAL_TIM_IRQHandler(). It makes a direct call to HAL_IncTick() to increment a global variable "uwTick" used as application time base.
Parameters
htim : TIM handle
Return values
None
Definition at line 661 of file main.c.
main()
int main (void)
The application entry point.
Return values
None
Definition at line 100 of file main.c.
References SystemClock_Config().
pwmOut()
void pwmOut (uint16_t a, uint16_t b, uint16_t c) inline
Set PWM duty cycle for a, b, and c outputs (12 bit inputs)
This function is used to set the duty cycle for each of the 3 pwm output waveforms by setting the timer compare register. It assumes a 12 bit input, thus bit shift..
Parameters
a The 12 bit duty cycle for tim2 channel 1 output
b The 12 bit duty cycle for tim2 channel 1 output
c The 12 bit duty cycle for tim2 channel 1 output
Definition at line 424 of file main.c.
setMotorTorque()
void setMotorTorque (int16_t torque)
When called, update the PWM output to keep specified torque (12 bit)
This function uses the encoder to calculate the correct phase to output via PWM to generate a field 90 degrees to the current location. Then this value is scaled by the ratio of torque/1000
Parameters
torque Controls how much 'torque' is applied from -1000 to 1000
Definition at line 441 of file main.c.
spiRead()
uint16_t spiRead (uint8_t addr)
Reads the value at the given address.
Transmits the address to read, then transmits again to get the response. This function then returns the value recieved via spi
Parameters
addr The address to read from the spi encoder
Returns
The value at the given address
Definition at line 523 of file main.c.
spiWrite()
uint16_t spiWrite (uint8_t addr, uint8_t val)
Writes val to the addr via SPI.
This function sets SS pin low, transmits the 16 bits (0x4000 | addr << 8 | val) and then releases SS pin. it returns the data recieved via spi.
Parameters
addr The address to write to
val The value to put in the address
Returns
The data recieved via spi
Definition at line 506 of file main.c.
StartDefaultTask()
void StartDefaultTask (void const * argument)
Task that sets up the pins, timers, etc. and run basic constant torque example.
This task configures the gpio to blink an led, enables interrupts for pwm input, starts the 3 pwm output channels, configures the spi encoder. Then, this task loops, blinking the led, updating torque, and printing the current angle of the motor via uart.
Parameters
argument Not used, but kept for rtos
Definition at line 577 of file main.c.
SystemClock_Config()
void SystemClock_Config (void)
System Clock Configuration.
Return values
None
Initializes the CPU, AHB and APB busses clocks
Initializes the CPU, AHB and APB busses clocks
Configure the Systick interrupt time
Configure the Systick
Definition at line 181 of file main.c.
References _Error_Handler().
Referenced by main().